# Generated by Django 5.0.6 on 2024-07-14 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='total_time_played',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
