# Generated by Django 5.0.6 on 2024-07-11 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='party',
            name='winner',
        ),
        migrations.AddField(
            model_name='newuser',
            name='in_waiting_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='score2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='user2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
