# Generated by Django 5.0.6 on 2024-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_alter_statistic_total_time_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='nbr_parties',
            field=models.IntegerField(default=0),
        ),
    ]
