# Generated by Django 5.0.6 on 2024-07-29 08:53

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0068_alter_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='draw_user_one',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draw_party_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='draw_user_two',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draw_party_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statistic',
            name='nbr_draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=255, unique=True),
        ),
    ]
