# Generated by Django 5.0.6 on 2024-07-29 09:25

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0069_party_draw_user_one_party_draw_user_two_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='draw_user_one',
        ),
        migrations.RemoveField(
            model_name='party',
            name='draw_user_two',
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=255, unique=True),
        ),
    ]
